version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "push to docker hub"
          command: |
            docker build -t osirisz/node-express-deploy:lastest .
            docker push osirisz/node-express-deploy:lastest
      - run:
          name: "deploy to rancher"
          command: |
            docker run --rm -it \
                -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
                -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
                -e CATTLE_URL="$CATTLE_URL" \
                etlweather/gaucho upgrade "1s19" \
                --imageUuid 'docker:osirisz/node-express-deploy:lastest' \
                --batch_size:2 --start_first \
                --auto_complete --timeout 600 \
            /
      - run: echo Done
